name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4.3.0
        with:
          java-version: 8
          distribution: "adopt"
          cache: "gradle"

      - name: Build with Gradle
        run: chmod +x ./gradlew && ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.4.0
        with:
          name: skidbounce
          path: build/libs/skidbounce-v?.?.?.jar
          if-no-files-found: error
